let PrivKey = require('yours-bitcoin/lib/priv-key')

let privKey = PrivKey.fromRandom()
console.log(privKey.toString())
let privKey2 = PrivKey.fromString(privKey.toString())
console.log(privKey2.toString())
console.log(privKey2.toJSON())
console.log(privKey2.toHex())
console.log(privKey2.toBuffer().toString('hex'))
console.log(privKey2.bn.toString())
let privKey3 = PrivKey.fromRandom()
let privKey3b = PrivKey.Mainnet.fromRandom()
let privKey4 = PrivKey.Testnet.fromRandom()
console.log(privKey3.toString())
console.log(privKey3b.toString())
console.log(privKey4.toString())
