'use strict'
let Sig = require('yours-bitcoin/lib/sig')
let Ecdsa = require('yours-bitcoin/lib/ecdsa')
let Hash = require('yours-bitcoin/lib/hash')
let KeyPair = require('yours-bitcoin/lib/key-pair')

let data = new Buffer('this is the data i want to sign')
let hash = Hash.sha256(data)
let keyPair = KeyPair.fromRandom()
let sig = Ecdsa.sign(hash, keyPair)
sig = Ecdsa.calcrecovery(sig, keyPair.pubKey, hash)
console.log(sig.toJSON())
console.log(sig.toDer().toString('hex'))
console.log(sig.toTxFormat().toString('hex'))
console.log(sig.toCompact().toString('hex'))
